/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hpPart1Sol from "./HPPart1.sol";
export type { hpPart1Sol };
import type * as hpPart2Sol from "./HPPart2.sol";
export type { hpPart2Sol };
import type * as hpPart3Sol from "./HPPart3.sol";
export type { hpPart3Sol };
import type * as hpdefiempireSol from "./Hpdefiempire.sol";
export type { hpdefiempireSol };
import type * as testtokenSol from "./Testtoken.sol";
export type { testtokenSol };
export type { Lock } from "./Lock";
export type { Pika } from "./Pika";
