/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IToken,
  ITokenInterface,
} from "../../../contracts/HPPart2.sol/IToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IToken__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenInterface {
    return new Interface(_abi) as ITokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IToken {
    return new Contract(address, _abi, runner) as unknown as IToken;
  }
}
